# This CI pipeline builds the project as a Docker image.
# It uses the Dockerfile found in the project root.
name: Build with Docker

on: push

jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # set up docker
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      # build the image
      - name: Build
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          # change this to push to docker hub
          push: false
          # change me!
          tags: DumbDogDiner/template-node:latest
