name: build

on: push

jobs:
  # standard build task
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # set up docker
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      # install deps
      - run: yarn install
      # run typescript compile
      - run: yarn build

  # docker build task
  build_docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # set up docker
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      # build the image
      - name: Build
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: false
          # change me!
          tags: DumbDogDiner/template-node:latest
