# This CI pipeline tests the project using Jest
name: Test with Jest

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # set up docker
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      # install deps
      - run: yarn install
      # run linter
      - run: yarn test
